<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>CivHub</title>
  <link rel="stylesheet" href="style.css">
</head>
<body>
  <header class="site-header">
    <div class="nav-container">
      <div class="nav-left"><a href="index.html">CivHub</a></div>
      <div class="nav-right"><a href="about.html">About</a></div>
    </div>
  </header>

  <main class="main-content">
    <section class="insight-feed">
      <article class="insight-item">
        <h3>🧠 Insight #008 – March 29, 2025</h3>
        <p>Between 2023–24 and 2024–25, <strong>Transportation</strong> saw a major budget increase in NY State—rising by over $1.1 billion. The largest single increase was to the MTA Payroll Mobility Tax, a key source of funding for public transit.</p>
        <img src="images/transportation_budget_mta_spike.png" alt="Transportation Budget MTA Spike" width="600">
        <small><em>Insight generated by CivHub AI v0.1</em></small>
        <small>Data Source: <a href="https://www.dropbox.com/scl/fi/4l3odmr42qslibimi5syf/ny_state_budget_cleaned-2.csv?rlkey=jk8hs94e8he4f5u5abg2gwvel&raw=1" target="_blank">NY State Budget (Cleaned)</a></small>
      </article>
      
      <article class="insight-item">
        <h3>🧠 Insight #007 – March 29, 2025</h3>
        <p>Among all NY budget functions, <strong>Economic Development</strong> saw the largest single-year drop in funding between 2023–24 and 2024–25—down over $460 million, with smaller cuts across Labor, Local Government, and Environmental agencies.</p>
        <img src="images/ny_budget_cuts_2024.png" alt="Top Budget Cuts by Function" width="600">
        <small><em>Insight generated by CivHub AI v0.1</em></small>
        <small>Data Source: <a href="https://www.dropbox.com/scl/fi/4l3odmr42qslibimi5syf/ny_state_budget_cleaned-2.csv?rlkey=jk8hs94e8he4f5u5abg2gwvel&raw=1" target="_blank">NY State Budget (Cleaned)</a></small>
      </article>

      <!-- Existing insights continue below -->
    </section>
  </main>

  <footer class="site-footer">
    <div class="footer-links">
      <a href="https://github.com/rhett-b/CivHub" target="_blank">GitHub</a>
      <a href="https://discord.gg/BAQxDSwz" target="_blank">Discord</a>
      <a href="https://medium.com/@civhubus" target="_blank">Medium</a>
      <a href="https://substack.com/@civhub" target="_blank">Substack</a>
      <a href="mailto:civhub.us@gmail.com">Email</a>
    </div>
    <div class="footer-copy">© 2025 CivHub. All rights reserved.</div>
  </footer>
</body>
</html>
